BEGIN;

-- =============================================================================
-- CONFIGURAÇÕES GERAIS DO SIGPREVI
-- =============================================================================
-- Armazena parâmetros globais da aplicação sem exigir alteração de código.
--
-- Exemplos:
-- - nome do sistema;
-- - nome da entidade;
-- - ambiente;
-- - manutenção;
-- - identidade institucional;
-- - parâmetros operacionais;
-- - configurações de módulos.
--
-- Valores sensíveis, como senhas, tokens, chaves privadas e credenciais,
-- não devem ser armazenados nesta tabela.
-- =============================================================================

CREATE TABLE app.system_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    key text NOT NULL,
    value jsonb NOT NULL DEFAULT '{}'::jsonb,

    category text NOT NULL DEFAULT 'general',
    description text,

    is_public boolean NOT NULL DEFAULT false,
    is_editable boolean NOT NULL DEFAULT true,
    is_system boolean NOT NULL DEFAULT false,

    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT system_settings_key_not_blank
        CHECK (length(trim(key)) > 0),

    CONSTRAINT system_settings_category_not_blank
        CHECK (length(trim(category)) > 0),

    CONSTRAINT system_settings_key_format
        CHECK (
            key ~ '^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)*$'
        ),

    CONSTRAINT system_settings_key_unique
        UNIQUE (key)
);

COMMENT ON TABLE app.system_settings IS
'Armazena configurações gerais, institucionais e operacionais do SIGPREVI.';

COMMENT ON COLUMN app.system_settings.key IS
'Identificador único da configuração no padrão categoria.chave.';

COMMENT ON COLUMN app.system_settings.value IS
'Valor da configuração armazenado em JSONB.';

COMMENT ON COLUMN app.system_settings.category IS
'Categoria lógica utilizada para organização e filtragem das configurações.';

COMMENT ON COLUMN app.system_settings.is_public IS
'Indica se a configuração pode ser consultada sem autenticação.';

COMMENT ON COLUMN app.system_settings.is_editable IS
'Indica se a configuração pode ser alterada pela interface administrativa.';

COMMENT ON COLUMN app.system_settings.is_system IS
'Indica configuração estrutural protegida contra exclusão comum.';

-- =============================================================================
-- TRIGGER DE UPDATED_AT
-- =============================================================================

CREATE TRIGGER trg_system_settings_updated_at
BEFORE UPDATE ON app.system_settings
FOR EACH ROW
EXECUTE FUNCTION app.set_updated_at();

-- =============================================================================
-- ÍNDICES
-- =============================================================================

CREATE INDEX idx_system_settings_category
    ON app.system_settings (category);

CREATE INDEX idx_system_settings_public
    ON app.system_settings (is_public)
    WHERE is_public = true;

CREATE INDEX idx_system_settings_value_gin
    ON app.system_settings
    USING gin (value);

-- =============================================================================
-- CONFIGURAÇÕES INICIAIS
-- =============================================================================

INSERT INTO app.system_settings (
    key,
    value,
    category,
    description,
    is_public,
    is_editable,
    is_system
)
VALUES
    (
        'system.name',
        to_jsonb('SIGPREVI'::text),
        'system',
        'Nome oficial da plataforma.',
        true,
        true,
        true
    ),
    (
        'system.full_name',
        to_jsonb(
            'Sistema Integrado de Gestão Previdenciária'::text
        ),
        'system',
        'Nome completo da plataforma.',
        true,
        true,
        true
    ),
    (
        'system.environment',
        to_jsonb('development'::text),
        'system',
        'Ambiente atual de execução da aplicação.',
        false,
        false,
        true
    ),
    (
        'system.maintenance_mode',
        'false'::jsonb,
        'system',
        'Indica se o sistema está em modo de manutenção.',
        false,
        true,
        true
    ),
    (
        'institution.name',
        to_jsonb('Mirassol-Previ'::text),
        'institution',
        'Nome institucional do RPPS.',
        true,
        true,
        true
    ),
    (
        'institution.legal_name',
        to_jsonb(
            'Fundo Municipal de Previdência Social dos Servidores de Mirassol d''Oeste'::text
        ),
        'institution',
        'Denominação jurídica completa da entidade.',
        true,
        true,
        true
    ),
    (
        'institution.municipality',
        to_jsonb('Mirassol d''Oeste'::text),
        'institution',
        'Município de vinculação do RPPS.',
        true,
        true,
        true
    ),
    (
        'institution.state',
        to_jsonb('MT'::text),
        'institution',
        'Unidade federativa da entidade.',
        true,
        true,
        true
    ),
    (
        'institution.country',
        to_jsonb('Brasil'::text),
        'institution',
        'País da entidade.',
        true,
        true,
        true
    ),
    (
        'institution.timezone',
        to_jsonb('America/Cuiaba'::text),
        'institution',
        'Fuso horário institucional utilizado pelo sistema.',
        true,
        true,
        true
    ),
    (
        'institution.locale',
        to_jsonb('pt-BR'::text),
        'institution',
        'Localidade padrão utilizada para datas, números e textos.',
        true,
        true,
        true
    ),
    (
        'security.audit_enabled',
        'true'::jsonb,
        'security',
        'Indica se a auditoria geral do sistema está habilitada.',
        false,
        false,
        true
    ),
    (
        'security.session_timeout_minutes',
        '60'::jsonb,
        'security',
        'Tempo padrão de inatividade antes da expiração da sessão.',
        false,
        true,
        true
    ),
    (
        'portal.base_url',
        to_jsonb('https://mirassolprevi.com.br'::text),
        'portal',
        'Endereço público principal do portal institucional.',
        true,
        true,
        true
    ),
    (
        'portal.legislation_enabled',
        'true'::jsonb,
        'portal',
        'Indica se a área pública de legislação está habilitada.',
        true,
        true,
        true
    )
ON CONFLICT (key)
DO UPDATE SET
    value = EXCLUDED.value,
    category = EXCLUDED.category,
    description = EXCLUDED.description,
    is_public = EXCLUDED.is_public,
    is_editable = EXCLUDED.is_editable,
    is_system = EXCLUDED.is_system,
    updated_at = now();

-- =============================================================================
-- ROW LEVEL SECURITY
-- =============================================================================

ALTER TABLE app.system_settings ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE app.system_settings FROM anon;
REVOKE ALL ON TABLE app.system_settings FROM authenticated;

GRANT SELECT ON TABLE app.system_settings TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE app.system_settings
TO authenticated;

-- Configurações públicas podem ser lidas por visitantes.

CREATE POLICY system_settings_select_public
ON app.system_settings
FOR SELECT
TO anon
USING (
    is_public = true
);

-- Usuários autenticados também podem consultar configurações públicas.

CREATE POLICY system_settings_select_public_authenticated
ON app.system_settings
FOR SELECT
TO authenticated
USING (
    is_public = true
);

-- Administradores e usuários autorizados podem consultar todas.

CREATE POLICY system_settings_select_authorized
ON app.system_settings
FOR SELECT
TO authenticated
USING (
    app.is_admin()
    OR app.has_permission('core.settings.read')
    OR app.has_permission('core.settings.manage')
);

-- Criação exige permissão de gestão.

CREATE POLICY system_settings_insert_authorized
ON app.system_settings
FOR INSERT
TO authenticated
WITH CHECK (
    app.is_admin()
    OR app.has_permission('core.settings.manage')
);

-- Alteração exige permissão e respeita is_editable.

CREATE POLICY system_settings_update_authorized
ON app.system_settings
FOR UPDATE
TO authenticated
USING (
    (
        app.is_admin()
        OR app.has_permission('core.settings.manage')
    )
    AND is_editable = true
)
WITH CHECK (
    (
        app.is_admin()
        OR app.has_permission('core.settings.manage')
    )
    AND is_editable = true
);

-- Configurações estruturais não podem ser excluídas pela API comum.

CREATE POLICY system_settings_delete_authorized
ON app.system_settings
FOR DELETE
TO authenticated
USING (
    (
        app.is_admin()
        OR app.has_permission('core.settings.manage')
    )
    AND is_system = false
);

-- =============================================================================
-- FUNÇÃO PARA CONSULTAR CONFIGURAÇÕES
-- =============================================================================

CREATE OR REPLACE FUNCTION app.get_system_setting(
    p_key text,
    p_default jsonb DEFAULT NULL
)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, app
AS $$
    SELECT COALESCE(
        (
            SELECT setting.value
            FROM app.system_settings AS setting
            WHERE setting.key = p_key
              AND (
                  setting.is_public = true
                  OR app.is_admin()
                  OR app.has_permission('core.settings.read')
                  OR app.has_permission('core.settings.manage')
              )
            LIMIT 1
        ),
        p_default
    );
$$;

COMMENT ON FUNCTION app.get_system_setting(text, jsonb) IS
'Retorna uma configuração do sistema pelo identificador, respeitando autorização.';

GRANT EXECUTE
ON FUNCTION app.get_system_setting(text, jsonb)
TO anon, authenticated;

-- =============================================================================
-- PROTEÇÃO DE CONFIGURAÇÕES ESTRUTURAIS
-- =============================================================================

CREATE OR REPLACE FUNCTION app.prevent_protected_setting_changes()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, app
AS $$
BEGIN
    IF TG_OP = 'DELETE' AND OLD.is_system = true THEN
        RAISE EXCEPTION
            'A configuração estrutural "%" não pode ser excluída.',
            OLD.key;
    END IF;

    IF TG_OP = 'UPDATE' THEN
        IF OLD.is_system = true AND NEW.key IS DISTINCT FROM OLD.key THEN
            RAISE EXCEPTION
                'O identificador da configuração estrutural "%" não pode ser alterado.',
                OLD.key;
        END IF;

        IF OLD.is_editable = false
           AND current_user NOT IN ('postgres', 'supabase_admin') THEN
            RAISE EXCEPTION
                'A configuração "%" não pode ser alterada diretamente.',
                OLD.key;
        END IF;
    END IF;

    RETURN CASE
        WHEN TG_OP = 'DELETE' THEN OLD
        ELSE NEW
    END;
END;
$$;

CREATE TRIGGER trg_protect_system_settings
BEFORE UPDATE OR DELETE ON app.system_settings
FOR EACH ROW
EXECUTE FUNCTION app.prevent_protected_setting_changes();

COMMIT;